### ISSUE TITLE
[BUG] Special Characters getting converted wrongly when cloned to mainframe DS

### ISSUE THREAD

**Issue by srlimkar** [zigi/zigi#339]
**Describe the bug**
Some of the special characters are not getting converted correctly when the repository is cloned on mainframe ds.

**Release of zigi**
ZIGI version 2.0

**To Reproduce**
1. Git .gitattributes file content as below:
![image](https://user-images.githubusercontent.com/57011223/78575730-5efff580-7849-11ea-8e8a-cd4cf109dc97.png)

2. Contents of .project file:

![image](https://user-images.githubusercontent.com/57011223/78575491-10eaf200-7849-11ea-8ced-a0fc4aede377.png)

3. file contents in GitHub as below
IF (VERIFY(CFLKA0Q_REC.CONTRACT_NBR,      
  ' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  
    !@#$^&;":,.>?<\/()-_+={}[]|`~') ¬= 0) 

4. file contents in Mainframe DS as below:
IF (VERIFY(CFLKA0Q_REC.CONTRACT_NBR,      
  ' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789  
    !@#$¬&;":,.>?<\/()-_+={}Ý¨|`~') Â^= 0)

Special Character Ú is replaced by something else have attached as the screen shot.
**Expected behavior**
Contents of the GitHub file and the contents of the Mainframe DS should be same.

**Screenshots**
![image](https://user-images.githubusercontent.com/57011223/78572197-c8313a00-7844-11ea-871d-663459202700.png)
![image](https://user-images.githubusercontent.com/57011223/78572326-f3b42480-7844-11ea-9ba3-01ed970ed012.png)

![image](https://user-images.githubusercontent.com/57011223/78572696-691ff500-7845-11ea-8e2c-7d8aeeac163f.png)

![image](https://user-images.githubusercontent.com/57011223/78572724-70470300-7845-11ea-8c52-1c2b038e1841.png)

**Additional context**

**Comment by wizardofzos** [comment]
Have you tried using a different codepage on the creation of the repo? Is your local codepage IBM-1047? Or do you have something else?

**Comment by bhavani316** [comment]
Codepage of my system is IBM-1047

**Comment by srlimkar** [comment]
Code page of my system is IBM-1047

**Comment by mfsysprog** [comment]
Codepages are a really difficult subject let alone when you start converting one into the other.

Without displaying your string in hex there is really not a lot that can be said for certain about your characters.
First of all, the codepage you specify for your terminal decides how a specific hexadecimal value will be displayed on your screen.
For example, the x'5B' value is a $ in the ibm-037 codepage. But if we set our 3270 emulator to the finnish codepage CP278 for example, the same x'5B' value will show up on your screen as Å. An indicator to the codepage your 3270 emulator is in is the ZTERMCID and friends. 
https://www.ibm.com/support/knowledgecenter/sl/SSLTBW_2.3.0/com.ibm.zos.v2r3.f54dg00/ispdg199.htm
If you have a dialog test option on your primary screen you can find that value under the variable option. Normally this is option 7.3 from the primary ispf panel.
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.f54u200/opv.htm

But most of the time, people use ibm-037. But you will see in the end that the interpretation of the hex value will become important at the end of this little story.

Next, we know from your .gitattributes that your files are considered iso8859-1. But if you edited your file with the web editor that some sites like github provide or some other windows based editor it might default to utf-8. And even though iso8859-1 and utf-8 have the same character mapping for the first 256 characters, the characters above 127 decimal are expressed as double byte characters in utf-8. So if whatever editor you use does not respect the iso8859-1 nature of your data it might corrupt things. And in your case the conversion of ¬ to Â^ is a very strong indicator that this is indeed what happened, because ¬ is x'C2AC' in utf-8 (double byte), but since they are translated  byte by byte the x'C2' translates as a Â. But that leaves the case how x'AC' was translated. In IBM-037 this should become x'5F', because that is ¬. But, we see a ^?  I'm guessing this is because in IBM-1047 the x'5F' is a ^.

So now the question is what editor did you use to show the contents of the mvs ds? And can you show it with hex on? And did you indeed edit the file in some 'utf-8 by default' editor?
